头发头饰:
  - 双马尾: twin tails
  - 马尾辫: pony tail
  - 发髻: hairbuns
  - 非常长头发: very long hair
  - 钻头头发: drill hair
  - 长刘海: eye-coveringbang
  - 角: horns
  - 兽耳: kemonomimi
  - 宝冠: tiara
  - 皇冠: crown
  - 耳机: headphones
面部特征与装饰:
  - 口枷: gag
  - 美人痣: beauty mark
  - 眼镜: glasses
  - 眼罩: blind fold
  - 雀斑: freckles
  - 不寻常的牙: unusual teeth
  - 不寻常的瞳孔: unusual pupils
  - 项圈: collar
  - 眼罩: eye patch
  - 眼部面具: eye mask
  - 鼻勾: nose hook
  - 黑瞳: dark sclera
  - 口罩: mouth mask
  - 异色瞳: heterochromia
  - 闭眼: closed eyes
  - 单眼: mono eye
表情:
  - 脸红: Blush
  - 张嘴: open mouth
  - 看着观众: looking at viewer
  - 病娇: yandere
  - 无表情: emotionless
身体:
  - 小胸: small breasts
  - 大胸: big breasts
  - 巨乳: huge breasts
  - 巨大乳房: gigantic breasts
  - 萝莉: lolicon
  - 肌肉: muscle
  - 孕妇: pregnant
  - 黑皮: dark skin
  - 反光黑皮: shiny dark skin
  - 油: oil
  - 晒痕: tanlines
  - 腋毛: hairy armpits
  - 淫纹: crotch tattoo
  - 全身刺青: full body tattoo
  - 娃娃的关节: doll joints
  - 疤痕: scar
  - 人体彩绘: body painting
  - 身体写作: body writing
  - 多毛: hairy
  - 石化: petrification
  - 欧派萝莉: oppai loli
  - 流汗: sweating
视角:
  - 从下向上看: viewed from below
  - 从后方看: back
动作:
  - 拉伸: Stretching
  - 钢管舞: pole dancing
  - 悬挂: hanging
  - 被抓握头发: prehensile hair
  - 践踏: trampling
  - 贞操锁: harness
  - 卡在墙上: stuck in wall
  - 挠痒: tickling
  - 泌乳: lactation
  - 挤奶: milking
  - 母乳喂养: breast feeding
  - 被截肢者: amputee
  - 舔脚: foot licking
  - 勾腿: leg lock
  - 折磨: torture
  - 打屁股: spanking
  - 醉酒: drunk
  - 束缚: shibari
  - 捆绑: bondage
  - 睡觉: sleeping
  - 接吻: kissing
制服类:
  - 幼儿园服: kindergarten uniform
  - 海盗: pirate
  - 牧师: priest
  - 服务员: waiter
  - 收银员: cashier
  - 女乘务员: stewardess
  - 忍者: ninja
  - 学校体育课服: school gym uniform
  - 女警: policewoman
  - 僵尸: zombie
  - 小精灵: fairy
  - 机械人女孩: mecha girl
  - 吸血鬼: vampire
  - 天使: angel
  - 女巫: witch
  - 新娘: bride
  - 啦啦队: cheerleader
  - 女服务员: waitress
  - 巫女: miko
  - 魔法少女: magical girl
  - 假小子: tomboy
  - 护士: nurse
  - 辣妹: gyaru
  - 兔女郎: bunny girl
  - 精灵: elf
  - 女仆: maid
  - 修女: sister
  - 奴隶: slave
  - 教练: coach
腿部:
  - 长袜: stockings
  - 连体袜: bodystocking
  - 吊带袜: garter belt
  - 连裤袜: pantyhose
  - 渔网: fishnets
  - 裸足: bare feet
  - 看重足部: foot focus
  - 高筒靴: thigh high boots
  - 镫骨式腿套: stirrup legwear
其他服饰:
  - 透明衣服: transparent clothing
  - 分离式袖子: detached sleeves
  - 紧身衣: tights
  - 裸体: nudity only
  - 运动短裤: gymshorts
  - 裸露的衣服: exposed clothing
  - 生活服装: living clothes
  - 哥特式洛丽塔: gothic lolita
  - 金属盔甲: metal armor
  - 缎带: bandages
  - 连衣裙: sundress
  - 连衣裙: leotard
  - 汉服: chinese dress
  - 乳贴: pasties
  - 白大褂: lab coat
  - 热裤: hotpants
  - 尾巴插件: tail plug
  - 运动服: tracksuit
  - 乳胶衣: latex
  - 自行车短裤: bike shorts
  - 连体衣: bodysuit
  - 军装: military
  - 商务套装: business suit
  - 泳装: swimsuit
  - 学校泳装: school swimsuit
  - 和服: kimono
  - 手套: gloves
  - 内衣: lingerie
  - 比基尼: bikini
  - 女学生制服: schoolgirl uniform
  - 围裙: apron
  - 尿布: diaper
  - 绳索: leash
  - 紧身胸衣: corset
  - 湿衣服: wet clothes
  - 阴部贴纸: vaginal sticker
  - 创可贴: bandaid
  - 肘部手套: elbow gloves
  - 白手套: white gloves
性交(R18):
  - 口交: Blowjob
  - 足交: Footjob
  - 足交: foot insertion
  - 撸管: Handjob
  - 多次手淫: multiple handjob
  - 肛交: anal intercourse
  - 肛交: analphagia
  - 兽交: bestiality
  - 腋下交: armpit sex
  - 乳胶: paizuri
  - 穿衣服乳胶: clothed paizuri
  - 深喉: deepthroat
  - 尾巴交: tailjob
  - 手淫: masturbation
  - 桌子自慰: table masturbation
  - 中出: nakadashi
  - 双重插入: double penetration
  - 手指指法: fingering
  - 舔阴: cunnilingus
  - 尿道口插入: urethra insertion
  - 子宫颈穿透: cervix penetration
  - 隐藏性爱: hidden sex
  - 电话性爱: phone sex
胸部(R18):
  - 大乳晕: big areolae
  - 乳房扩张: breast expansion
  - 拳交: fisting
  - 大乳头: big nipples
  - 操乳头: nipple fuck
  - 黑乳头: dark nipples
  - 乳头内陷: inverted nipples
  - 乳头扩张: nipple expansion
  - 乳头刺激: nipple stimulation
阴部(R18):
  - 避孕套: condom
  - 双阴道: double vaginal
  - 漱口: gaping
  - 大阴蒂: big clit
  - 阴毛: pubic stubble
  - 阴蒂生长: clit growth
  - 阴蒂刺激: clit stimulation
  - 潮吹: squirting
  - 排尿: urination
BDSM(R18):
  - 肛门: anal
  - 大肛门: big ass
  - 露阴癖: exhibitionism
  - 嗑药: drugs
  - 穿环: piercing
  - 情趣用品: sex toys
  - 胃部破坏: stomach deformation
  - 腹部膨胀: inflation
  - 羞辱: humiliation
  - 饮尿: piss drinking
  - 大型插入物: large insertions
  - 贞操带: chastity belt
  - 电击: electric shocks
  - 鞭子: whip
  - 强制暴露: forced exposure
  - 夹子: clamp
  - 肛门分娩: anal birth
  - 大阴道: big vagina
  - 子宫颈脱垂: cervix prolapse
  - 残疾: handicapped
  - 肛门脱垂: anal prolapse
  - 屁眼扩张: ass expansion
  - 不寻常插入: unusual insertions
  - 人格排泄: personality excretion
  - 窥视器: speculum
  - 木马: wooden horse
  - 唾液: saliva
  - 注射器: syringe
  - 窒息: asphyxiation
  - 人类宠物: human pet
  - 洗脑: mind break
  - 催眠: mind control
  - 女性主导: femdom
  - 漏尿: omorashi
  - 恶堕: corruption
  - 肉便器: public use
  - 排泄: scat
面部(R18):
  - 阿黑颜: ahegao
  - 口交脸: blowjob face
  - 颜射: bukkake
  - 射精到眼睛里: cum in eye